object Version {
    //App Level
    const val toolsBuildGradle = "7.4.2"
    const val crashlyticsGradle = "2.9.4"
    const val gmsGradle = "4.3.15"
    const val kotlinGradle = "1.8.10"
    const val protobufGradle = "0.8.18"
    const val composeCompiler = "1.4.3"

    //Project Level
    const val accompanist = "0.28.0"
    const val activityCompose = "1.6.1"
    const val chucker = "3.5.2"
    const val coil = "2.2.2"
    const val composeAnimation = "1.3.3"
    const val composeFoundation = "1.3.1"
    const val composeMaterial = "1.3.1"
    const val composeRuntime = "1.3.3"
    const val composeUi = "1.3.3"
    const val constraintLayoutCompose = "1.0.1"
    const val coreKtx = "1.8.0"
    const val coreSplashScreen = "1.0.0-beta02"
    const val coroutines = "1.6.4"
    const val datastore = "1.0.0"
    const val espresso = "3.5.1"
    const val extJUnit = "1.1.5"
    const val firebase = "31.2.3"
    const val firebaseUI = "8.0.2"
    const val gmsPlayServicesAuth = "20.4.0"
    const val hilt = "2.45"
    const val hiltCompose = "1.0.0"
    const val jUnit = "4.13.2"
    const val lifecycle = "2.5.1"
    const val material = "1.6.0"
    const val moshi = "1.14.0"
    const val navigationCompose = "2.5.3"
    const val okHttp = "4.10.0"
    const val paging = "3.1.1"
    const val pagingCompose = "1.0.0-alpha18"
    const val protobuf = "3.22.1"
    const val retrofit = "2.9.0"
    const val room = "2.5.0"
    const val spotless = "6.16.0"
    const val test = "1.5.0"
    const val webkit = "1.6.0"
}