object Version {
    //App Level
    const val toolsBuildGradle = "7.2.1"
    const val crashlyticsGradle = "2.9.0"
    const val googleMapsSecretGradle = "2.0.1"
    const val googleMapsServices = "4.3.10"
    const val hiltGradle = "2.42"
    const val kotlinGradle = "1.6.10"

    //Project Level
    const val accompanist = "0.23.1"
    const val activityCompose = "1.4.0"
    const val chucker = "3.5.2"
    const val coil = "2.1.0"
    const val compose = "1.1.1"
    const val constraintLayoutCompose = "1.0.1"
    const val coreKtx = "1.8.0"
    const val coreSplashScreen = "1.0.0-beta02"
    const val coroutines = "1.6.2"
    const val crashlytics = "2.9.0"
    const val datastore = "1.0.0"
    const val espresso = "3.4.0"
    const val extJUnit = "1.1.3"
    const val firebase = "30.1.0"
    const val firebaseUI = "8.0.1"
    const val gmsGoogleServices = "4.3.10"
    const val gmsPlayServicesAuth = "20.2.0"
    const val gson = "2.9.0"
    const val hilt = "2.42"
    const val hiltCompose = "1.0.0"
    const val jUnit = "4.13.2"
    const val kotlin = "1.6.10"
    const val lifecycle = "2.4.1"
    const val material = "1.6.0"
    const val moshi = "1.13.0"
    const val navigationCompose = "2.4.2"
    const val okHttp = "4.9.3"
    const val paging = "3.1.1"
    const val pagingCompose = "1.0.0-alpha15"
    const val protobuf = "3.21.1"
    const val protobufGradle = "0.8.18"
    const val retrofit = "2.9.0"
    const val room = "2.4.1"
    const val reflect = "1.7.0"
    const val test = "1.4.0"
    const val webkit = "1.4.0"
}